version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8081:8080"   # Jenkins UI
      - "50000:50000" # agent
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock    # allow Jenkins to build Docker images on host
      - $HOME/.kube:/root/.kube:ro                    # kubeconfig so Jenkins can run kubectl (ensure your kubeconfig path)
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

volumes:
  jenkins_home:
